version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    networks:
      - backend
  booksrv:
    # image: book-service:latest
    depends_on:
      - mongo
    ports:
      - "5001:8000"
    expose:
      - 8000
    volumes:
      - type: bind
        source: ./book
        target: /app
    restart: always
    networks:
      - backend
networks:
  backend:
    driver: bridge
