name: assignment3

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log Start Time
        run: |
          echo "$(date -Iminutes)" > log.txt

      - name: Add submitter names to log
        run: echo "Yuval Maliniak, Rotem Mizrachi" >> log.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: ./book
          file: ./book/Dockerfile
          tags: book-service:latest
          outputs: type=docker,dest=/tmp/image.tar

      - name: Log build success
        if: success()
        run: echo "image successfully built" >> log.txt

      - name: Log build failure
        if: failure()
        run: echo "image not able to be built" >> log.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: book-service
          path: /tmp/image.tar

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Log_file
          path: log.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4

      - name: Load Docker images from artifact
        run: docker load --input book-service/image.tar

      - name: Set up Docker Compose
        run: docker-compose -f ./docker-compose.yml up -d

      - name: Check container is running
        run: docker ps

      - name: Log container status
        run: |
          if grep -q "image successfully built" Log_file/log.txt; then
            if docker-compose -f ./docker-compose.yml ps | grep -q "Up"; then
              echo "Container up and running" >> Log_file/log.txt
            else
              echo "Container failed to run" >> Log_file/log.txt
            fi
          fi

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: Run pytest tests
        run: |
          pytest -v ./tests/assn3_tests.py > assn3_test_results.txt

      - name: Log test results
        if: always()
        run: |
          if grep -q "Container up and running" Log_file/log.txt; then
            if grep -q "FAILED" assn3_test_results.txt; then
              echo "tests failed" >> Log_file/log.txt
            else
              echo "tests succeeded" >> Log_file/log.txt
            fi
          fi
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: assn3_test_results
          path: assn3_test_results.txt

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Log_file
          path: Log_file/log.txt
          overwrite: true

      - name: Tear down Docker Compose
        run: docker-compose -f ./docker-compose.yml down

  query:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4

      - name: Load Docker images from artifact
        run: docker load --input book-service/image.tar

      - name: Set up Docker Compose
        run: docker-compose -f ./docker-compose.yml up -d

      - name: Check container is running
        run: docker ps

      - name: POST Books
        run: |
            # Define books as JSON strings
            book1='{"title":"Adventures of Huckleberry Finn","ISBN":"9780520343641","genre":"Fiction"}'
            book2='{"title":"The Best of Isaac Asimov","ISBN":"9780385050784","genre":"Science Fiction"}'
            book3='{"title":"Fear No Evil","ISBN":"9780394558783","genre":"Biography"}'
            book6='{"title":"The Adventures of Tom Sawyer","ISBN":"9780195810400","genre":"Fiction"}'
            book7='{"title":"I, Robot","ISBN":"9780553294385","genre":"Science Fiction"}'
            book8='{"title":"Second Foundation","ISBN":"9780553293364","genre":"Science Fiction"}'
            sleep 10
            # Perform POST requests using curl or similar
            curl -X POST -m 10 -H "Content-Type: application/json" -d "$book1" http://127.0.0.1:5001/books
            curl -X POST -m 10 -H "Content-Type: application/json" -d "$book2" http://127.0.0.1:5001/books
            curl -X POST -m 10 -H "Content-Type: application/json" -d "$book3" http://127.0.0.1:5001/books
            curl -X POST -m 10 -H "Content-Type: application/json" -d "$book6" http://127.0.0.1:5001/books
            curl -X POST -m 10 -H "Content-Type: application/json" -d "$book7" http://127.0.0.1:5001/books
            curl -X POST -m 10 -H "Content-Type: application/json" -d "$book8" http://127.0.0.1:5001/books

      - name: Read query.txt file
        run: |
          cat query.txt | while read line
          do
            # Perform GET request for each query string
            response=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:5001/books$line")
        
            # Check if response is successful (status code 200)
            if [ $response -eq 200 ]; then
                json=$(curl -s "http://localhost:5001/books$line")
                echo "query: $line" >> response.txt
                echo "response: $json" >> response.txt
            else
                # Handle error status code
                echo "query: $line" >> response.txt
                echo "response: error $response" >> response.txt
            fi
          done

      - name: Upload response.txt
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: response-results
          path: response.txt

      - name: Tear down Docker Compose
        run: docker-compose -f ./docker-compose.yml down
